

services:
  postgres:
    image: postgres:13
    container_name: nest_postgres
    restart: always
    environment:
      POSTGRES_USER: shashank_vaish
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nestdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  

volumes:
  pgdata: